$(document).ready(function(){
  $("button#hide").click(function(){
    $("#test").hide(1000);
  });
  $("button#show").click(function(){
	 $("#test").show(1000); 
  });
  $("button#slow").click(function(){
	 $("#test").show("slow"); 
  });
  $("button#fast").click(function(){
	 $("#test").show("fast"); 
  });
});